name: s6_http
description: A one hour exercise, based on the Darrrt project, to learn AngularDart.
dependencies:
  angular: 0.14.0
  browser: any
  js: any
  shadow_dom: any
  unittest: any
transformers:
- angular